
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dev Gerald
 */
public class GamePlay extends javax.swing.JFrame {

    /**
     * Creates new form GamePlay
     */
    public GamePlay() {
        initComponents();
    }
    
    // Initialization
    // For random number from 1 - 10
    int max = 10;
    int min = 1;
    int secretNumber = (int) Math.floor(Math.random() *(max - min + 1) + min);
    //For chances
    int attemps = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title2Panel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        title1Panel = new javax.swing.JPanel();
        numberTitleLabel = new javax.swing.JLabel();
        gameplayPanel = new javax.swing.JPanel();
        resultTextField = new javax.swing.JTextField();
        attempsTitleLabel = new javax.swing.JLabel();
        attempsLabel = new javax.swing.JLabel();
        checkButton = new javax.swing.JButton();
        answerTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Number Guessing Game");
        setBackground(new java.awt.Color(204, 204, 204));
        setLocation(new java.awt.Point(0, 0));
        setName("GameplayFrame"); // NOI18N
        setResizable(false);

        title2Panel.setBackground(new java.awt.Color(204, 204, 204));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setText("Number Guessing Game");

        descriptionLabel.setText("Guess the secret number from 1 to 10");

        javax.swing.GroupLayout title2PanelLayout = new javax.swing.GroupLayout(title2Panel);
        title2Panel.setLayout(title2PanelLayout);
        title2PanelLayout.setHorizontalGroup(
            title2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(title2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        title2PanelLayout.setVerticalGroup(
            title2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title2PanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionLabel)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        title1Panel.setBackground(new java.awt.Color(204, 255, 204));

        numberTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        numberTitleLabel.setText("1-10");

        javax.swing.GroupLayout title1PanelLayout = new javax.swing.GroupLayout(title1Panel);
        title1Panel.setLayout(title1PanelLayout);
        title1PanelLayout.setHorizontalGroup(
            title1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title1PanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(numberTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        title1PanelLayout.setVerticalGroup(
            title1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title1PanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(numberTitleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gameplayPanel.setBackground(new java.awt.Color(255, 255, 255));

        resultTextField.setEditable(false);
        resultTextField.setBackground(new java.awt.Color(204, 255, 204));
        resultTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resultTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        resultTextField.setText("Guess The Number");
        resultTextField.setFocusable(false);
        resultTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultTextFieldActionPerformed(evt);
            }
        });

        attempsTitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        attempsTitleLabel.setText("Attemps:");

        attempsLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        attempsLabel.setText("0");

        checkButton.setText("Check");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Guess here");

        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Note: Upto 3 attemps only");

        javax.swing.GroupLayout gameplayPanelLayout = new javax.swing.GroupLayout(gameplayPanel);
        gameplayPanel.setLayout(gameplayPanelLayout);
        gameplayPanelLayout.setHorizontalGroup(
            gameplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameplayPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(gameplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(gameplayPanelLayout.createSequentialGroup()
                        .addComponent(attempsTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(attempsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(95, 95, 95))
            .addGroup(gameplayPanelLayout.createSequentialGroup()
                .addGroup(gameplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameplayPanelLayout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addGroup(gameplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(answerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(gameplayPanelLayout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gameplayPanelLayout.setVerticalGroup(
            gameplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameplayPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(resultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(gameplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attempsTitleLabel)
                    .addComponent(attempsLabel))
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(answerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkButton)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(title2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(gameplayPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(title1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(gameplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resultTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultTextFieldActionPerformed

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
        // This is to get the value that the player inputed
        // Use try catch in case the player inputed a letter. Assign 0 if the inputed value is not int.
        int guess;
        try {
            guess = Integer.parseInt(answerTextField.getText());
        } catch (NumberFormatException e) {
            guess = 0;
        }
        
        // To check if the guess inputed is withing the range of 1 - 10;
        if(guess >= 1 && guess <= 10) {
       
            //To add attemps
            attemps++;
            attempsLabel.setText(String.valueOf(attemps));
           
            //To test the number guess by the player
            // And also to check if the player already tried 3 times
            if(guess == secretNumber || attemps == 3) {
                // To check if the player guess the secret number
                if(guess == secretNumber){
                    // If the player guesses the right answer call the function to show 
                    // the result and add the win parameter to declare that
                    // the call comes from the win decision
                    showResult("win");
                } else {
                    // If the player failed to guess the secret number call the function to show
                    // the result and add the lose parameter to declare that
                    // the call comes from the lose decision
                    showResult("lose");
                }
            } else if(guess > secretNumber){
                resultTextField.setText("Lower");
            } else {
                resultTextField.setText("Higher");
            }
        } else { 
            resultTextField.setText("Please input 1 to 10 number only");
        }
        
    }//GEN-LAST:event_checkButtonActionPerformed
    
    // Function to show the game result and ask to play agian or quit
    public void showResult(String result) {
        // To test what message title of the result
        // This is either win or lose
        // If win show title as You Win else show You Lose
        String resultTitle = result.equals("win") ? "You Win" : "You Lose";
        
        //To test what is the message content of the result
        // The same with the result title above
        String resultMessage = result.equals("win") ? "Congratulation! You got it in " + String.valueOf(attemps) + " attemps!" + "\nSecret number is " + secretNumber + "." : "Sorry, 3 attempts already.\nSecret number is " + secretNumber + ".";
        
        // This is to ask if the player wants to play again
        String[] options = new String[]{"Play again", "Quit"};
        var input = JOptionPane.showOptionDialog(null, resultMessage, resultTitle, JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);

        // This is to check the player response
        // 0 Play Again
        // 1 Quit
        if(input == 0){
           // If Play Again
           attemps = 0;
           secretNumber = (int) Math.floor(Math.random() *(max - min + 1) + min);
           answerTextField.setText("");
           resultTextField.setText("Guess The Number");
           attempsLabel.setText(String.valueOf(attemps));
        } else {
            // If Quit
            this.dispose();
        }
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamePlay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answerTextField;
    private javax.swing.JLabel attempsLabel;
    private javax.swing.JLabel attempsTitleLabel;
    private javax.swing.JButton checkButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JPanel gameplayPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel numberTitleLabel;
    private javax.swing.JTextField resultTextField;
    private javax.swing.JPanel title1Panel;
    private javax.swing.JPanel title2Panel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
